// TochelinGuide
export const REQUEST_LIST__TOCHELIN_GUIDE = 'REQUEST_LIST__TOCHELIN_GUIDE';
export const RECEIVE_LIST__TOCHELIN_GUIDE = 'RECEIVE_LIST__TOCHELIN_GUIDE';
export const FAILURE_LIST__TOCHELIN_GUIDE = 'FAILURE_LIST__TOCHELIN_GUIDE';

// TochelinGuideFilters
export const SET_FILTER__TOCHELIN_GUIDE_FILTERS = 'SET_FILTER__TOCHELIN_GUIDE_FILTERS';

// YachelinGuide
export const REQUEST_LIST__YACHELIN_GUIDE = 'REQUEST_LIST__YACHELIN_GUIDE';
export const RECEIVE_LIST__YACHELIN_GUIDE = 'RECEIVE_LIST__YACHELIN_GUIDE';
export const FAILURE_LIST__YACHELIN_GUIDE = 'FAILURE_LIST__YACHELIN_GUIDE';

// BochelinGuide
export const REQUEST_LIST__BOCHELIN_GUIDE = 'REQUEST_LIST__BOCHELIN_GUIDE';
export const RECEIVE_LIST__BOCHELIN_GUIDE = 'RECEIVE_LIST__BOCHELIN_GUIDE';
export const FAILURE_LIST__BOCHELIN_GUIDE = 'FAILURE_LIST__BOCHELIN_GUIDE';
