// tochelinFilters
export const TOGGLE_FILTER__TOCHELIN_FILTER = 'TOGGLE_FILTER__TOCHELIN_FILTER';

// TochelinGuide
export const REQUEST_LIST__TOCHELIN_GUIDE = 'REQUEST_LIST__TOCHELIN_GUIDE';
export const RECEIVE_LIST__TOCHELIN_GUIDE = 'RECEIVE_LIST__TOCHELIN_GUIDE';
export const FAILURE_LIST__TOCHELIN_GUIDE = 'FAILURE_LIST__TOCHELIN_GUIDE';

// YachelinGuide
export const REQUEST_LIST__YACHELIN_GUIDE = 'REQUEST_LIST__YACHELIN_GUIDE';
export const RECEIVE_LIST__YACHELIN_GUIDE = 'RECEIVE_LIST__YACHELIN_GUIDE';
export const FAILURE_LIST__YACHELIN_GUIDE = 'FAILURE_LIST__YACHELIN_GUIDE';

// BochelinGuide
export const REQUEST_LIST__BOCHELIN_GUIDE = 'REQUEST_LIST__BOCHELIN_GUIDE';
export const RECEIVE_LIST__BOCHELIN_GUIDE = 'RECEIVE_LIST__BOCHELIN_GUIDE';
export const FAILURE_LIST__BOCHELIN_GUIDE = 'FAILURE_LIST__BOCHELIN_GUIDE';
